const PRIMARY_COLOR = '#008848';
const PRIMARY_LIGHT = '#45DD95';
const SECONDARY_COLOR = '#ec212f';
const SECONDARY_LIGHT = '#ec212f';
const RED_LIGHT = '#FC7A83'
export {
  PRIMARY_COLOR,
  SECONDARY_COLOR,
  PRIMARY_LIGHT,
  SECONDARY_LIGHT,
  RED_LIGHT
};
